version: "3.9"

services:

  db:
    image: postgres:16
    container_name: tasks_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Xdecker123
      POSTGRES_DB: task_manager
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: tasks_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Xdecker123@db:5432/task_manager
      JWT_SECRET: 774437823accca4e9d923b76003f42c7
    depends_on:
      - db

volumes:
  postgres_data: