# -------- BASE --------
    FROM node:20-alpine AS base
    WORKDIR /app
    
    # -------- DEPENDENCIES --------
    FROM base AS deps
    COPY package*.json ./
    RUN npm install
    
    # -------- BUILD --------
    FROM base AS builder
    COPY --from=deps /app/node_modules ./node_modules
    COPY . .
    RUN npx prisma generate
    RUN npm run build
    
    # -------- PRODUCTION --------
    FROM node:20-alpine AS runner
    WORKDIR /app
    
    ENV NODE_ENV=production
    
    COPY package*.json ./
    RUN npm install --omit=dev
    
    COPY --from=builder /app/dist ./dist
    COPY --from=builder /app/prisma ./prisma
    COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
    COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
    
    EXPOSE 3000
    
    CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed && node dist/src/main.js"]