# -------- BASE --------
    FROM node:20-alpine AS base
    WORKDIR /app
    
    # -------- DEPENDENCIES --------
    FROM base AS deps
    COPY package*.json ./
    RUN npm install
    
    # -------- BUILD --------
    FROM base AS builder
    COPY --from=deps /app/node_modules ./node_modules
    COPY . .
    RUN npm run build
    
    # -------- PRODUCTION --------
    FROM node:20-alpine AS runner
    WORKDIR /app
    
    ENV NODE_ENV=production
    
    COPY package*.json ./
    RUN npm install --omit=dev
    
    COPY --from=builder /app/.next ./.next
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/node_modules ./node_modules
    COPY --from=builder /app/package.json ./package.json
    
    EXPOSE 3001
    
    CMD ["npm", "start", "--", "-p", "3001"]